/** ==================================================================================================================================
 * @file     variadic.hpp
 * @author   Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
 * @date     Thursday, 30th December 2021 4:42:02 pm
 * @modified Thursday, 3rd February 2022 11:37:42 am
 * @project  Winder
 * @brief
 *    
 *    Header undefining macros defined in the variadic.hpp file
 *    
 * @copyright Krzysztof Pierczyk © 2021
 * ================================================================================================================================ */

#ifdef __ESTD_PREPROCESSOR_VARIADIC_H__

/* ========================================================== Namespaces ========================================================== */

#ifdef VARIADIC_ELEM_0
#undef VARIADIC_ELEM_0
#endif

#ifdef VARIADIC_ELEM_1
#undef VARIADIC_ELEM_1
#endif

#ifdef VARIADIC_ELEM_2
#undef VARIADIC_ELEM_2
#endif

#ifdef VARIADIC_ELEM_3
#undef VARIADIC_ELEM_3
#endif

#ifdef VARIADIC_ELEM_4
#undef VARIADIC_ELEM_4
#endif

#ifdef VARIADIC_ELEM_5
#undef VARIADIC_ELEM_5
#endif

#ifdef VARIADIC_ELEM_6
#undef VARIADIC_ELEM_6
#endif

#ifdef VARIADIC_ELEM_7
#undef VARIADIC_ELEM_7
#endif

#ifdef VARIADIC_ELEM_8
#undef VARIADIC_ELEM_8
#endif

#ifdef VARIADIC_ELEM_9
#undef VARIADIC_ELEM_9
#endif

#ifdef VARIADIC_ELEM_10
#undef VARIADIC_ELEM_10
#endif

#ifdef VARIADIC_ELEM_11
#undef VARIADIC_ELEM_11
#endif

#ifdef VARIADIC_ELEM_12
#undef VARIADIC_ELEM_12
#endif

#ifdef VARIADIC_ELEM_13
#undef VARIADIC_ELEM_13
#endif

#ifdef VARIADIC_ELEM_14
#undef VARIADIC_ELEM_14
#endif

#ifdef VARIADIC_ELEM_15
#undef VARIADIC_ELEM_15
#endif

#ifdef VARIADIC_ELEM_16
#undef VARIADIC_ELEM_16
#endif

#ifdef VARIADIC_ELEM_17
#undef VARIADIC_ELEM_17
#endif

#ifdef VARIADIC_ELEM_18
#undef VARIADIC_ELEM_18
#endif

#ifdef VARIADIC_ELEM_19
#undef VARIADIC_ELEM_19
#endif

#ifdef VARIADIC_ELEM_20
#undef VARIADIC_ELEM_20
#endif

#ifdef VARIADIC_ELEM_21
#undef VARIADIC_ELEM_21
#endif

#ifdef VARIADIC_ELEM_22
#undef VARIADIC_ELEM_22
#endif

#ifdef VARIADIC_ELEM_23
#undef VARIADIC_ELEM_23
#endif

#ifdef VARIADIC_ELEM_24
#undef VARIADIC_ELEM_24
#endif

#ifdef VARIADIC_ELEM_25
#undef VARIADIC_ELEM_25
#endif

#ifdef VARIADIC_ELEM_26
#undef VARIADIC_ELEM_26
#endif

#ifdef VARIADIC_ELEM_27
#undef VARIADIC_ELEM_27
#endif

#ifdef VARIADIC_ELEM_28
#undef VARIADIC_ELEM_28
#endif

#ifdef VARIADIC_ELEM_29
#undef VARIADIC_ELEM_29
#endif

#ifdef VARIADIC_ELEM_30
#undef VARIADIC_ELEM_30
#endif

#ifdef VARIADIC_ELEM_31
#undef VARIADIC_ELEM_31
#endif

#ifdef VARIADIC_ELEM_32
#undef VARIADIC_ELEM_32
#endif

#ifdef VARIADIC_ELEM_33
#undef VARIADIC_ELEM_33
#endif

#ifdef VARIADIC_ELEM_34
#undef VARIADIC_ELEM_34
#endif

#ifdef VARIADIC_ELEM_35
#undef VARIADIC_ELEM_35
#endif

#ifdef VARIADIC_ELEM_36
#undef VARIADIC_ELEM_36
#endif

#ifdef VARIADIC_ELEM_37
#undef VARIADIC_ELEM_37
#endif

#ifdef VARIADIC_ELEM_38
#undef VARIADIC_ELEM_38
#endif

#ifdef VARIADIC_ELEM_39
#undef VARIADIC_ELEM_39
#endif

#ifdef VARIADIC_ELEM_40
#undef VARIADIC_ELEM_40
#endif

#ifdef VARIADIC_ELEM_41
#undef VARIADIC_ELEM_41
#endif

#ifdef VARIADIC_ELEM_42
#undef VARIADIC_ELEM_42
#endif

#ifdef VARIADIC_ELEM_43
#undef VARIADIC_ELEM_43
#endif

#ifdef VARIADIC_ELEM_44
#undef VARIADIC_ELEM_44
#endif

#ifdef VARIADIC_ELEM_45
#undef VARIADIC_ELEM_45
#endif

#ifdef VARIADIC_ELEM_46
#undef VARIADIC_ELEM_46
#endif

#ifdef VARIADIC_ELEM_47
#undef VARIADIC_ELEM_47
#endif

#ifdef VARIADIC_ELEM_48
#undef VARIADIC_ELEM_48
#endif

#ifdef VARIADIC_ELEM_49
#undef VARIADIC_ELEM_49
#endif

#ifdef VARIADIC_ELEM_50
#undef VARIADIC_ELEM_50
#endif

#ifdef VARIADIC_ELEM_51
#undef VARIADIC_ELEM_51
#endif

#ifdef VARIADIC_ELEM_52
#undef VARIADIC_ELEM_52
#endif

#ifdef VARIADIC_ELEM_53
#undef VARIADIC_ELEM_53
#endif

#ifdef VARIADIC_ELEM_54
#undef VARIADIC_ELEM_54
#endif

#ifdef VARIADIC_ELEM_55
#undef VARIADIC_ELEM_55
#endif

#ifdef VARIADIC_ELEM_56
#undef VARIADIC_ELEM_56
#endif

#ifdef VARIADIC_ELEM_57
#undef VARIADIC_ELEM_57
#endif

#ifdef VARIADIC_ELEM_58
#undef VARIADIC_ELEM_58
#endif

#ifdef VARIADIC_ELEM_59
#undef VARIADIC_ELEM_59
#endif

#ifdef VARIADIC_ELEM_60
#undef VARIADIC_ELEM_60
#endif

#ifdef VARIADIC_ELEM_61
#undef VARIADIC_ELEM_61
#endif

#ifdef VARIADIC_ELEM_62
#undef VARIADIC_ELEM_62
#endif

#ifdef VARIADIC_ELEM_63
#undef VARIADIC_ELEM_63
#endif

#ifdef VARIADIC_ELEM
#undef VARIADIC_ELEM
#endif

#ifdef VARIADIC_FIRST_1_ELEMS
#undef VARIADIC_FIRST_1_ELEMS
#endif

#ifdef VARIADIC_FIRST_2_ELEMS
#undef VARIADIC_FIRST_2_ELEMS
#endif

#ifdef VARIADIC_FIRST_3_ELEMS
#undef VARIADIC_FIRST_3_ELEMS
#endif

#ifdef VARIADIC_FIRST_4_ELEMS
#undef VARIADIC_FIRST_4_ELEMS
#endif

#ifdef VARIADIC_FIRST_5_ELEMS
#undef VARIADIC_FIRST_5_ELEMS
#endif

#ifdef VARIADIC_FIRST_6_ELEMS
#undef VARIADIC_FIRST_6_ELEMS
#endif

#ifdef VARIADIC_FIRST_7_ELEMS
#undef VARIADIC_FIRST_7_ELEMS
#endif

#ifdef VARIADIC_FIRST_8_ELEMS
#undef VARIADIC_FIRST_8_ELEMS
#endif

#ifdef VARIADIC_FIRST_9_ELEMS
#undef VARIADIC_FIRST_9_ELEMS
#endif

#ifdef VARIADIC_FIRST_10_ELEMS
#undef VARIADIC_FIRST_10_ELEMS
#endif

#ifdef VARIADIC_FIRST_11_ELEMS
#undef VARIADIC_FIRST_11_ELEMS
#endif

#ifdef VARIADIC_FIRST_12_ELEMS
#undef VARIADIC_FIRST_12_ELEMS
#endif

#ifdef VARIADIC_FIRST_13_ELEMS
#undef VARIADIC_FIRST_13_ELEMS
#endif

#ifdef VARIADIC_FIRST_14_ELEMS
#undef VARIADIC_FIRST_14_ELEMS
#endif

#ifdef VARIADIC_FIRST_15_ELEMS
#undef VARIADIC_FIRST_15_ELEMS
#endif

#ifdef VARIADIC_FIRST_16_ELEMS
#undef VARIADIC_FIRST_16_ELEMS
#endif

#ifdef VARIADIC_FIRST_17_ELEMS
#undef VARIADIC_FIRST_17_ELEMS
#endif

#ifdef VARIADIC_FIRST_18_ELEMS
#undef VARIADIC_FIRST_18_ELEMS
#endif

#ifdef VARIADIC_FIRST_19_ELEMS
#undef VARIADIC_FIRST_19_ELEMS
#endif

#ifdef VARIADIC_FIRST_20_ELEMS
#undef VARIADIC_FIRST_20_ELEMS
#endif

#ifdef VARIADIC_FIRST_21_ELEMS
#undef VARIADIC_FIRST_21_ELEMS
#endif

#ifdef VARIADIC_FIRST_22_ELEMS
#undef VARIADIC_FIRST_22_ELEMS
#endif

#ifdef VARIADIC_FIRST_23_ELEMS
#undef VARIADIC_FIRST_23_ELEMS
#endif

#ifdef VARIADIC_FIRST_24_ELEMS
#undef VARIADIC_FIRST_24_ELEMS
#endif

#ifdef VARIADIC_FIRST_25_ELEMS
#undef VARIADIC_FIRST_25_ELEMS
#endif

#ifdef VARIADIC_FIRST_26_ELEMS
#undef VARIADIC_FIRST_26_ELEMS
#endif

#ifdef VARIADIC_FIRST_27_ELEMS
#undef VARIADIC_FIRST_27_ELEMS
#endif

#ifdef VARIADIC_FIRST_28_ELEMS
#undef VARIADIC_FIRST_28_ELEMS
#endif

#ifdef VARIADIC_FIRST_29_ELEMS
#undef VARIADIC_FIRST_29_ELEMS
#endif

#ifdef VARIADIC_FIRST_30_ELEMS
#undef VARIADIC_FIRST_30_ELEMS
#endif

#ifdef VARIADIC_FIRST_31_ELEMS
#undef VARIADIC_FIRST_31_ELEMS
#endif

#ifdef VARIADIC_FIRST_32_ELEMS
#undef VARIADIC_FIRST_32_ELEMS
#endif

#ifdef VARIADIC_FIRST_33_ELEMS
#undef VARIADIC_FIRST_33_ELEMS
#endif

#ifdef VARIADIC_FIRST_34_ELEMS
#undef VARIADIC_FIRST_34_ELEMS
#endif

#ifdef VARIADIC_FIRST_35_ELEMS
#undef VARIADIC_FIRST_35_ELEMS
#endif

#ifdef VARIADIC_FIRST_36_ELEMS
#undef VARIADIC_FIRST_36_ELEMS
#endif

#ifdef VARIADIC_FIRST_37_ELEMS
#undef VARIADIC_FIRST_37_ELEMS
#endif

#ifdef VARIADIC_FIRST_38_ELEMS
#undef VARIADIC_FIRST_38_ELEMS
#endif

#ifdef VARIADIC_FIRST_39_ELEMS
#undef VARIADIC_FIRST_39_ELEMS
#endif

#ifdef VARIADIC_FIRST_40_ELEMS
#undef VARIADIC_FIRST_40_ELEMS
#endif

#ifdef VARIADIC_FIRST_41_ELEMS
#undef VARIADIC_FIRST_41_ELEMS
#endif

#ifdef VARIADIC_FIRST_42_ELEMS
#undef VARIADIC_FIRST_42_ELEMS
#endif

#ifdef VARIADIC_FIRST_43_ELEMS
#undef VARIADIC_FIRST_43_ELEMS
#endif

#ifdef VARIADIC_FIRST_44_ELEMS
#undef VARIADIC_FIRST_44_ELEMS
#endif

#ifdef VARIADIC_FIRST_45_ELEMS
#undef VARIADIC_FIRST_45_ELEMS
#endif

#ifdef VARIADIC_FIRST_46_ELEMS
#undef VARIADIC_FIRST_46_ELEMS
#endif

#ifdef VARIADIC_FIRST_47_ELEMS
#undef VARIADIC_FIRST_47_ELEMS
#endif

#ifdef VARIADIC_FIRST_48_ELEMS
#undef VARIADIC_FIRST_48_ELEMS
#endif

#ifdef VARIADIC_FIRST_49_ELEMS
#undef VARIADIC_FIRST_49_ELEMS
#endif

#ifdef VARIADIC_FIRST_50_ELEMS
#undef VARIADIC_FIRST_50_ELEMS
#endif

#ifdef VARIADIC_FIRST_51_ELEMS
#undef VARIADIC_FIRST_51_ELEMS
#endif

#ifdef VARIADIC_FIRST_52_ELEMS
#undef VARIADIC_FIRST_52_ELEMS
#endif

#ifdef VARIADIC_FIRST_53_ELEMS
#undef VARIADIC_FIRST_53_ELEMS
#endif

#ifdef VARIADIC_FIRST_54_ELEMS
#undef VARIADIC_FIRST_54_ELEMS
#endif

#ifdef VARIADIC_FIRST_55_ELEMS
#undef VARIADIC_FIRST_55_ELEMS
#endif

#ifdef VARIADIC_FIRST_56_ELEMS
#undef VARIADIC_FIRST_56_ELEMS
#endif

#ifdef VARIADIC_FIRST_57_ELEMS
#undef VARIADIC_FIRST_57_ELEMS
#endif

#ifdef VARIADIC_FIRST_58_ELEMS
#undef VARIADIC_FIRST_58_ELEMS
#endif

#ifdef VARIADIC_FIRST_59_ELEMS
#undef VARIADIC_FIRST_59_ELEMS
#endif

#ifdef VARIADIC_FIRST_60_ELEMS
#undef VARIADIC_FIRST_60_ELEMS
#endif

#ifdef VARIADIC_FIRST_61_ELEMS
#undef VARIADIC_FIRST_61_ELEMS
#endif

#ifdef VARIADIC_FIRST_62_ELEMS
#undef VARIADIC_FIRST_62_ELEMS
#endif

#ifdef VARIADIC_FIRST_63_ELEMS
#undef VARIADIC_FIRST_63_ELEMS
#endif

#ifdef VARIADIC_FIRST_64_ELEMS
#undef VARIADIC_FIRST_64_ELEMS
#endif

#ifdef VARIADIC_FIRST_N_ELEMS
#undef VARIADIC_FIRST_N_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_1_ELEMS
#undef VARIADIC_REMOVE_FIRST_1_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_2_ELEMS
#undef VARIADIC_REMOVE_FIRST_2_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_3_ELEMS
#undef VARIADIC_REMOVE_FIRST_3_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_4_ELEMS
#undef VARIADIC_REMOVE_FIRST_4_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_5_ELEMS
#undef VARIADIC_REMOVE_FIRST_5_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_6_ELEMS
#undef VARIADIC_REMOVE_FIRST_6_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_7_ELEMS
#undef VARIADIC_REMOVE_FIRST_7_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_8_ELEMS
#undef VARIADIC_REMOVE_FIRST_8_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_9_ELEMS
#undef VARIADIC_REMOVE_FIRST_9_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_10_ELEMS
#undef VARIADIC_REMOVE_FIRST_10_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_11_ELEMS
#undef VARIADIC_REMOVE_FIRST_11_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_12_ELEMS
#undef VARIADIC_REMOVE_FIRST_12_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_13_ELEMS
#undef VARIADIC_REMOVE_FIRST_13_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_14_ELEMS
#undef VARIADIC_REMOVE_FIRST_14_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_15_ELEMS
#undef VARIADIC_REMOVE_FIRST_15_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_16_ELEMS
#undef VARIADIC_REMOVE_FIRST_16_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_17_ELEMS
#undef VARIADIC_REMOVE_FIRST_17_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_18_ELEMS
#undef VARIADIC_REMOVE_FIRST_18_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_19_ELEMS
#undef VARIADIC_REMOVE_FIRST_19_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_20_ELEMS
#undef VARIADIC_REMOVE_FIRST_20_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_21_ELEMS
#undef VARIADIC_REMOVE_FIRST_21_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_22_ELEMS
#undef VARIADIC_REMOVE_FIRST_22_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_23_ELEMS
#undef VARIADIC_REMOVE_FIRST_23_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_24_ELEMS
#undef VARIADIC_REMOVE_FIRST_24_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_25_ELEMS
#undef VARIADIC_REMOVE_FIRST_25_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_26_ELEMS
#undef VARIADIC_REMOVE_FIRST_26_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_27_ELEMS
#undef VARIADIC_REMOVE_FIRST_27_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_28_ELEMS
#undef VARIADIC_REMOVE_FIRST_28_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_29_ELEMS
#undef VARIADIC_REMOVE_FIRST_29_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_30_ELEMS
#undef VARIADIC_REMOVE_FIRST_30_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_31_ELEMS
#undef VARIADIC_REMOVE_FIRST_31_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_32_ELEMS
#undef VARIADIC_REMOVE_FIRST_32_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_33_ELEMS
#undef VARIADIC_REMOVE_FIRST_33_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_34_ELEMS
#undef VARIADIC_REMOVE_FIRST_34_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_35_ELEMS
#undef VARIADIC_REMOVE_FIRST_35_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_36_ELEMS
#undef VARIADIC_REMOVE_FIRST_36_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_37_ELEMS
#undef VARIADIC_REMOVE_FIRST_37_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_38_ELEMS
#undef VARIADIC_REMOVE_FIRST_38_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_39_ELEMS
#undef VARIADIC_REMOVE_FIRST_39_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_40_ELEMS
#undef VARIADIC_REMOVE_FIRST_40_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_41_ELEMS
#undef VARIADIC_REMOVE_FIRST_41_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_42_ELEMS
#undef VARIADIC_REMOVE_FIRST_42_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_43_ELEMS
#undef VARIADIC_REMOVE_FIRST_43_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_44_ELEMS
#undef VARIADIC_REMOVE_FIRST_44_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_45_ELEMS
#undef VARIADIC_REMOVE_FIRST_45_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_46_ELEMS
#undef VARIADIC_REMOVE_FIRST_46_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_47_ELEMS
#undef VARIADIC_REMOVE_FIRST_47_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_48_ELEMS
#undef VARIADIC_REMOVE_FIRST_48_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_49_ELEMS
#undef VARIADIC_REMOVE_FIRST_49_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_50_ELEMS
#undef VARIADIC_REMOVE_FIRST_50_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_51_ELEMS
#undef VARIADIC_REMOVE_FIRST_51_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_52_ELEMS
#undef VARIADIC_REMOVE_FIRST_52_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_53_ELEMS
#undef VARIADIC_REMOVE_FIRST_53_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_54_ELEMS
#undef VARIADIC_REMOVE_FIRST_54_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_55_ELEMS
#undef VARIADIC_REMOVE_FIRST_55_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_56_ELEMS
#undef VARIADIC_REMOVE_FIRST_56_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_57_ELEMS
#undef VARIADIC_REMOVE_FIRST_57_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_58_ELEMS
#undef VARIADIC_REMOVE_FIRST_58_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_59_ELEMS
#undef VARIADIC_REMOVE_FIRST_59_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_60_ELEMS
#undef VARIADIC_REMOVE_FIRST_60_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_61_ELEMS
#undef VARIADIC_REMOVE_FIRST_61_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_62_ELEMS
#undef VARIADIC_REMOVE_FIRST_62_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_63_ELEMS
#undef VARIADIC_REMOVE_FIRST_63_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_64_ELEMS
#undef VARIADIC_REMOVE_FIRST_64_ELEMS
#endif

#ifdef VARIADIC_REMOVE_FIRST_N_ELEMS
#undef VARIADIC_REMOVE_FIRST_N_ELEMS
#endif

/* ================================================================================================================================ */

#undef __ESTD_PREPROCESSOR_VARIADIC_H__
#endif
